#Cabecera del deployment 
apiVersion: v1  #Versi칩n de la API que usaremos.
kind: Service #Espemecificaremos el tipo de objeto que definiremos
#Metadatos del service
metadata:
  name: nginx #Nombre del service
  labels:
    run: nginx #Etiqueta a침adida al service
#Especificaciones de la maquina.
spec:
  ports: #Puertos que se publicar치n.
  - port: 80 #Puerto donde se publicar치 
    protocol: TCP #Tipo de protocolo que utilizara la app.
  selector: #Con selector se define el conjunto de pods.
    run: nginx #Etiqueta del selector por la cual se agrupan los pods.
  type: LoadBalancer #Tipo de acceso desde el exterior.